version: '3.9'

services:
  app:
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    command: python challenge/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  
  tests:
    tty: true
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    command: pytest challenge
    volumes:
      - .:/app
    profiles:
      - donotstart
